comet/config.go
=> unmatch config

comet/comet-example.conf, comet/config.go, comet/main.go, comet/rpc_push.go
=> support rpc push

comet/log.xml, logic/job/pushs/log.xml, logic/log.xml, router/log.xml
=> log.xml false

client-example/client.js, client-example/demo.html
=> add js client demo

benchmark/client/main.go
=> timeout bug

comet/bucket.go, comet/room.go
=> fix del room bug

comet/comet-example.conf, comet/config.go, comet/main.go, comet/slow.go, comet/tcp.go, comet/websocket.go
=> add slow log

comet/slow.go, comet/tcp.go, comet/websocket.go
=> optimize slow

benchmark/client/main.go, comet/room.go, comet/slow.go, comet/tcp.go, comet/websocket.go
1.slow log support multi type
2.benchmark client support reconnect
=> slow log support multi type

benchmark/client/main.go, benchmark/push_room/main.go, comet/main.go, comet/room.go, comet/slow.go, comet/tcp.go, comet/websocket.go
=> fix slow crush

comet/websocket.go, libs/proto/proto.go, libs/time/timer.go
batch部分是我们目前在用的方式， 我们现在用json的消息， 而且客户端没有做协议实现。
=> 改用gorilla/websocket实现

benchmark/push/main.go
=> fix benchmark bug

comet/comet-example.conf, comet/config.go, comet/main.go, comet/monitor.go, comet/rpc.go, libs/net/xrpc/clients.go, libs/proto/comet.go, logic/config.go, logic/job/comet.go, logic/job/comet_info.go, logic/job/config.go, logic/job/job-example.conf, logic/job/main.go, logic/job/monitor.go, logic/job/room.go, logic/logic-example.conf, logic/main.go, logic/monitor.go, router/bucket.go, router/config.go, router/main.go, router/monitor.go, router/router-example.conf, router/rpc.go
1. fix room ids & room counts.
2. add monitor.
=> fix roomIds & add monitor

comet/rpc.go, libs/time/timer.go, libs/time/timer_test.go, router/test/router_test.go
Router 提供的RPC调用中没有 Connect 和 DisConnect, 作者指的应该是 Put 和 Del
=> fix router test ;fix timer test

internal/logic/dao/dao.go
=> refactor newKafkaPub function in  dao.go

internal/comet/bucket.go
=> 修复切房间造成的房间内链表回路

pkg/websocket/conn.go
websocket连接被comet主动断开.
使用websocket成功连接后,连续快速的发送小包(150字节左右).
很快即可重现该问题.
由于 `pkg/bufio/bufio.go` 包中`Pop`函数返回的切片与底层`buf`切片共享部分数据.
且在执行`Pop`的过程中,可能会调用`b.fill()`而引发底层`buf`切片的数据移动.
`copy(b.buf, b.buf[b.r:b.w]) `
所以在后续执行`Pop`过程中,并不能保证前面执行`Pop`返回的切片里面的值不发生变化.
所以在`pkg/websocket/conn.go`的`readFrame`函数中,
依次执行`maskKey, err = c.r.Pop(4)`和`payload, err = c.r.Pop(int(payloadLen))`后
并不能百分百保证`maskBytes(maskKey, 0, payload) `使用的`maskKey`还是之前的值.
这样有可能会导致解码数据出错.
最终会大概率导致`api/comet/grpc/protocol.go`的`ReadWebsocket`函数校验包长时出错.
https://github.com/Terry-Mao/goim/blob/d5d3d0ebd4608571b71f65cbd800bb0b8e9e84fa/pkg/websocket/conn.go#L226-L241
https://github.com/Terry-Mao/goim/blob/d5d3d0ebd4608571b71f65cbd800bb0b8e9e84fa/pkg/bufio/bufio.go#L156-L163
https://github.com/Terry-Mao/goim/blob/d5d3d0ebd4608571b71f65cbd800bb …
=> 修复websocket协议解析数据帧时可能出错的问题

internal/logic/balancer.go, internal/logic/balancer_test.go
=> fix wrong character

pkg/time/timer.go
pkg/timer 最小堆算法有问题，修改了一下，麻烦查阅！
=> fix timer minheap issue

internal/comet/operation.go
=> fix filed name error
